### ISSUE TITLE
[Upgrade to Next 12] - WIP

### ISSUE THREAD

**Issue by payapula** [payapula/blog#45]
## Description

To update repo to use latest version of nextJS.

There is branch WIP - [feature/update_next_and_its_deps](https://github.com/payapula/blog/tree/feature/update_next_and_its_deps)

It has the latest version of the following libraries

- chakra
- next
- next-seo
- next-mdx-remote

![image](https://user-images.githubusercontent.com/7134153/142756045-f8451e19-55b1-436f-84a9-8987ec32f416.png)

## Issues

1. Faced an issue with **node version**, as next bumped the minimum required node version from 12.0 to 12.22

Solution: Use bash terminal which has the latest node version, v14.7.5

> Nvm is installed in bash terminal
> If nvm common not found in bash then troubleshoot - https://github.com/nvm-sh/nvm#troubleshooting-on-linux
> bash: source ~/.bashrc
> Then bash should by default have node version 14x
> node —version
> v14.7.5

2. Unable to start the server. **React is not defined**

![image](https://user-images.githubusercontent.com/7134153/142756138-30f0c386-8943-42fc-bedd-4a5036fa8157.png)

~~This is because next now uses SWC compiler instead of babel. Chakra uses emotion which has a dependency on [babel plugin](https://www.npmjs.com/package/@emotion/babel-plugin).~~

~~The porting of this babel plugin into SWC is in progress - [Port @emotion/babel-plugin to SWC](https://github.com/vercel/next.js/issues/30804). Hence, waiting for it to complete the next update.~~

The issue was because of [JSX pragma](https://emotion.sh/docs/css-prop#jsx-pragma) being used to style some of the elements in the components. As a workaround, those css props were removed and replaced with chakra props 😄.

This is no longer a blocker.

## Progress Overview

- [x] Update chakra
- [x] Update next and all related deps
- [x]  Fix node issue
- [x] Fix React not defined issue

**Comment by payapula** [comment]
Faced one more issue, because of chakra upgrade from 1.3 to 1.7. https://github.com/chakra-ui/chakra-ui/issues/4226#issuecomment-904630320.

For a workaround, I have removed the `ThemeOverride` type for overrides - [commit](https://github.com/payapula/blog/commit/7eeacacbba5e2181fed27e4bfdebf64c05804853)

**Comment by ruansenadev** [comment]
Next 12 also forces an *incremental* config in tsconfig.js, which makes union from chakra-ui theme don't show at all, and it's a very annoying bug because it doesn't notice in logs and we can't differ if was a config in IDE or was that from packages versions..

**Comment by payapula** [comment]
Hi @ruansenadev 

I am not quite sure what is the issue you are facing. I am guessing it's related to the type of theme we are passing to `extendTheme` function and tsconfig. 

I didn't face any issue with chara-ui theme being displayed when I write code. If you give an example I will check if it's happening for me or not. 

Thank you.
